# Generated by Django 3.0.6 on 2024-09-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20240908_2005'),
        ('stores', '0002_auto_20240908_1958'),
    ]

    operations = [
    ]
